version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  
  app:
    container_name: book
    build:
      context: .
    ports:
      - "80:3000" 
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/votre_db
    networks:
      - app-network
  
volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
